import { Product, Order } from '@/types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p001',
    name: '冷蔵庫 406L 2ドア',
    brand: 'SHARP',
    category: '冷蔵庫',
    grade: 'A',
    status: 'AVAILABLE',
    monthlyPrice: 4800,
    description: '2ドア冷蔵庫。冷凍室・冷蔵室ともに清潔。動作確認済み。',
    sourceLocation: '品川区回収',
    refurbishedAt: '2026-05-15',
    serialNo: 'SH-RF001',
    createdAt: '2026-05-20',
  },
  {
    id: 'p002',
    name: '全自動洗濯機 6kg',
    brand: 'Panasonic',
    category: '洗濯機',
    grade: 'A',
    status: 'AVAILABLE',
    monthlyPrice: 3200,
    description: '全自動洗濯機。槽洗浄済み。静音設計。',
    sourceLocation: '渋谷区回収',
    refurbishedAt: '2026-05-20',
    serialNo: 'PA-WM002',
    createdAt: '2026-05-25',
  },
  {
    id: 'p003',
    name: '電子レンジ 700W',
    brand: 'Toshiba',
    category: '電子レンジ',
    grade: 'A',
    status: 'AVAILABLE',
    monthlyPrice: 1500,
    description: '単機能電子レンジ。フラットテーブル。清掃済み。',
    sourceLocation: '新宿区回収',
    refurbishedAt: '2026-06-01',
    serialNo: 'TO-MW003',
    createdAt: '2026-06-05',
  },
  {
    id: 'p004',
    name: '空気清浄機 〜14畳',
    brand: 'Daikin',
    category: 'その他家電',
    grade: 'A',
    status: 'AVAILABLE',
    monthlyPrice: 2200,
    description: '空気清浄機。フィルター交換済み。PM2.5対応。',
    sourceLocation: '目黒区回収',
    refurbishedAt: '2026-06-10',
    serialNo: 'DA-AP004',
    createdAt: '2026-06-12',
  },
  {
    id: 'p005',
    name: '冷蔵庫 540L 3ドア',
    brand: 'Hitachi',
    category: '冷蔵庫',
    grade: 'B',
    status: 'AVAILABLE',
    monthlyPrice: 5800,
    description: '大容量3ドア冷蔵庫。外装に軽微な傷あり（Bランク）。動作は完全。',
    sourceLocation: '世田谷区回収',
    refurbishedAt: '2026-06-05',
    serialNo: 'HI-RF005',
    createdAt: '2026-06-08',
  },
  {
    id: 'p006',
    name: '洗濯乾燥機 8kg',
    brand: 'Panasonic',
    category: '洗濯機',
    grade: 'A',
    status: 'RENTED',
    monthlyPrice: 5500,
    description: '洗濯乾燥機。ドラム式。ヒートポンプ乾燥。',
    sourceLocation: '港区回収',
    refurbishedAt: '2026-04-20',
    serialNo: 'PA-WD006',
    createdAt: '2026-04-25',
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord001',
    userId: 'u001',
    productId: 'p006',
    status: 'ACTIVE',
    startDate: '2026-05-01',
    minEndDate: '2026-08-01',
    monthlyPrice: 5500,
    deliveryAddress: '東京都渋谷区渋谷3-6-7',
    createdAt: '2026-04-28',
    product: MOCK_PRODUCTS.find(p => p.id === 'p006'),
  },
]

export const CATEGORIES = ['すべて', '冷蔵庫', '洗濯機', '電子レンジ', 'その他家電']
